name: Issue to PR using Aider
on:
  issues:
    types: [labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write
    
jobs:
  generate:
    uses: oscoreio/ai-workflows/.github/workflows/issue-to-pr-using-aider.yml@main
    if: startsWith(github.event.label.name, 'aider')
    with:
      issue-number: ${{ github.event.issue.number }}
      default-branch: ${{ github.event.repository.default_branch }}
      install-command: "npm install"
      test-command: "npx next build"
      autofix-command: "npx next lint --fix"
    secrets:
      openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY }}
      openai-api-key: ${{ secrets.OPENAI_API_KEY }}
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
      groq-api-key: ${{ secrets.GROQ_API_KEY }}
      gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
      cohere-api-key: ${{ secrets.COHERE_API_KEY }}
      deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}
